runtime: python312
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SECRET_KEY: "your-production-secret-key-change-this"
  GCP_PROJECT_ID: "game-store-assignment"
  CLOUD_SQL_CONNECTION_NAME: "game-store-assignment:europe-west2:gamestore-sql"
  DB_NAME: "gamestore"
  DB_USER: "postgres"
  DB_PASSWORD: "ASSIGNMENT2026"

beta_settings:
  cloud_sql_instances: "game-store-assignment:europe-west2:gamestore-sql"

instance_class: F1

handlers:
- url: /static
  static_dir: app/static
  
- url: /.*
  script: auto
  secure: always