runtime: python312
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SECRET_KEY: "your-production-secret-key-change-this"
  GCP_PROJECT_ID: "game-store-assignment"
  CLOUD_SQL_CONNECTION_NAME: "game-store-assignment:europe-west2:gamestore-sql"
  DB_NAME: "game-store-assignment"
  DB_USER: "postgres"
  DB_PASSWORD: "ASSIGNMENT2026"
  
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: app/static
  
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301